# Generated by Django 2.2.10 on 2020-03-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20200225_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ('-created',)},
        ),
    ]
