# Generated by Django 2.2.10 on 2020-03-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20200316_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={},
        ),
    ]
