# Generated by Django 2.2.10 on 2020-03-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_auto_20200322_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ('created',)},
        ),
    ]
