# Generated by Django 2.2.10 on 2020-05-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_auto_20200323_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={},
        ),
        migrations.AlterField(
            model_name='rate',
            name='buy',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'USD'), (2, 'EUR'), (3, 'RUB')]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sale',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
